development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: b2b_dev
  pool: 20
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: client_nhsbikes_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: b2b_prod
  pool: 20
  username: root
  password: