require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CinelistsController do

  # This should return the minimal set of attributes required to create a valid
  # Cinelist. As you add validations to Cinelist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "object_response" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CinelistsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cinelists as @cinelists" do
      cinelist = Cinelist.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cinelists).should eq([cinelist])
    end
  end

  describe "GET show" do
    it "assigns the requested cinelist as @cinelist" do
      cinelist = Cinelist.create! valid_attributes
      get :show, {:id => cinelist.to_param}, valid_session
      assigns(:cinelist).should eq(cinelist)
    end
  end

  describe "GET new" do
    it "assigns a new cinelist as @cinelist" do
      get :new, {}, valid_session
      assigns(:cinelist).should be_a_new(Cinelist)
    end
  end

  describe "GET edit" do
    it "assigns the requested cinelist as @cinelist" do
      cinelist = Cinelist.create! valid_attributes
      get :edit, {:id => cinelist.to_param}, valid_session
      assigns(:cinelist).should eq(cinelist)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cinelist" do
        expect {
          post :create, {:cinelist => valid_attributes}, valid_session
        }.to change(Cinelist, :count).by(1)
      end

      it "assigns a newly created cinelist as @cinelist" do
        post :create, {:cinelist => valid_attributes}, valid_session
        assigns(:cinelist).should be_a(Cinelist)
        assigns(:cinelist).should be_persisted
      end

      it "redirects to the created cinelist" do
        post :create, {:cinelist => valid_attributes}, valid_session
        response.should redirect_to(Cinelist.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cinelist as @cinelist" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cinelist.any_instance.stub(:save).and_return(false)
        post :create, {:cinelist => { "object_response" => "invalid value" }}, valid_session
        assigns(:cinelist).should be_a_new(Cinelist)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cinelist.any_instance.stub(:save).and_return(false)
        post :create, {:cinelist => { "object_response" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cinelist" do
        cinelist = Cinelist.create! valid_attributes
        # Assuming there are no other cinelists in the database, this
        # specifies that the Cinelist created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cinelist.any_instance.should_receive(:update_attributes).with({ "object_response" => "MyString" })
        put :update, {:id => cinelist.to_param, :cinelist => { "object_response" => "MyString" }}, valid_session
      end

      it "assigns the requested cinelist as @cinelist" do
        cinelist = Cinelist.create! valid_attributes
        put :update, {:id => cinelist.to_param, :cinelist => valid_attributes}, valid_session
        assigns(:cinelist).should eq(cinelist)
      end

      it "redirects to the cinelist" do
        cinelist = Cinelist.create! valid_attributes
        put :update, {:id => cinelist.to_param, :cinelist => valid_attributes}, valid_session
        response.should redirect_to(cinelist)
      end
    end

    describe "with invalid params" do
      it "assigns the cinelist as @cinelist" do
        cinelist = Cinelist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cinelist.any_instance.stub(:save).and_return(false)
        put :update, {:id => cinelist.to_param, :cinelist => { "object_response" => "invalid value" }}, valid_session
        assigns(:cinelist).should eq(cinelist)
      end

      it "re-renders the 'edit' template" do
        cinelist = Cinelist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cinelist.any_instance.stub(:save).and_return(false)
        put :update, {:id => cinelist.to_param, :cinelist => { "object_response" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cinelist" do
      cinelist = Cinelist.create! valid_attributes
      expect {
        delete :destroy, {:id => cinelist.to_param}, valid_session
      }.to change(Cinelist, :count).by(-1)
    end

    it "redirects to the cinelists list" do
      cinelist = Cinelist.create! valid_attributes
      delete :destroy, {:id => cinelist.to_param}, valid_session
      response.should redirect_to(cinelists_url)
    end
  end

end
